spring:
  profiles:
    active: local

  application:
    name: mockstock-live

  autoconfigure:
    exclude:
      - org.springframework.boot.micrometer.metrics.autoconfigure.export.prometheus.PrometheusMetricsExportAutoConfiguration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    org.hibernate.SQL: info
